### PR TITLE
📝 Add-Quote: 1 new quote from @pratheek-raghunath

### PR DESCRIPTION
**Pull request by pratheek-raghunath**
### Description
added 3 quotes

### Additional context

---

### What is the purpose of this pull request? 

- [x] Add quotes
- [ ] Bug fix
- [ ] New Feature
- [ ] Add more tests
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123` or `closes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by AnilSeervi — CHANGES_REQUESTED** [review]
Can you please follow the [Contributing guidelines](https://github.com/AnilSeervi/inspirational-quotes/blob/main/CONTRIBUTING.md) and make the necessary change according to that.
Otherwise the formatter/linter is going to fail.

**Comment by pratheek-raghunath** [comment]
Corrected. Please verify.

**Review by pratheek-raghunath — COMMENTED** [review]
Corrected according to the contribution.md

**Review by AnilSeervi — APPROVED** [review]
Thanks for contributing to the project @pratheek-raghunath
I've made the necessary changes myself.

**Pull request merged**
