### PR TITLE
feat(devcontainer): add the ability to use GitHub Codespaces and VS Code remote containers

### PR DESCRIPTION
**Pull request by andrewbrey**
### Description

This project is marked as open to contribution for `Hacktoberfest`, and as such I figured it would be desirable for contributors to have a simplified means of getting up and running with the developer setup. With the addition of the `devcontainer` configuration, this project is now compatible with `GitHub Codespaces` as well as `VS Code Remote Containers`. Contributors who use one of these options now get all of the dev setup steps completed for them, and you get peace of mind that contributions will come from setups with the correct usage of eslint, prettier, vitest, etc.

### Additional context

**Demo using GH Codespaces**

[Demo](https://user-images.githubusercontent.com/34140052/194139365-c5b3249a-1c66-4b06-b4a4-b4e88697b940.mp4)

---

### What is the purpose of this pull request? 

- [ ] Add quotes
- [ ] Bug fix
- [x] New Feature
- [ ] Add more tests
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123` or `closes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by AnilSeervi — APPROVED** [review]
Hi @andrewbrey, I myself use GitHub Codespaces to make the edits.
Thanks for adding the support for remote containers. I've also made some changes by adding vscode settings.
Happy Hacking!

**Comment by andrewbrey** [comment]
@AnilSeervi Great! Any idea why the `build (12.x)` check is not making progress? It's been unchanged for like 12 hours :smile:

**Comment by AnilSeervi** [comment]
> @AnilSeervi Great! Any idea why the `build (12.x)` check is not making progress? It's been unchanged for like 12 hours 😄

No idea @andrewbrey.I haven't even put `12.x` node version in the workflow and still it expects for it.

**Comment by andrewbrey** [comment]
@AnilSeervi perhaps you could merge this PR (without that check being completed) and take a look at your GH actions setup separately? :smile: 

**EDIT:**: For what it's worth, the `actions/setup-node` action is on `v2` in your `test.yml`, but the latest version of that action is `v3`...maybe it's a bug in that action? https://github.com/actions/setup-node

**Pull request merged**
